apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleSchedule
metadata:
  name: schedule
  namespace: janus-argocd
spec:
  connection_secret: aap-access
  name: ${{ values.component_id }}-volume-snapshots
  rrule: "DTSTART:20210101T000000Z RRULE:FREQ=DAILY;INTERVAL=1;COUNT=1"
  unified_job_template: ${{ values.component_id }}-volume-snapshots