apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleSchedule
metadata:
  name: ${{ values.component_id}}-snap-schedule
  namespace: janus-argocd
spec:
  connection_secret: aap-access
  name: "${{ values.component_id}}-Snapshot Schedule"
  unified_job_template: snapshot-${{values.component_id}}-template
  rrule: "DTSTART:20210101T000000Z RRULE:INTERVAL=1;FREQ=HOURLY"